### ISSUE TITLE
deploy by expm module, raise Scrivener is not available

### ISSUE THREAD

**Issue by lidashuang** [rrrene/elixirstatus-web#28]
use exrm

exrm 

```
      {:exrm, "~> 0.19.2"}
```
Elixir version 1.0.5

`mix phoenix.server` is ok,

but `rel/elixir_status/bin/elixir_status console` will raise undefined function: Scrivener.paginate/4  exception

```
22:51:54 lds@where elixirstatus-web slug ? rel/elixir_status/bin/elixir_status console
Using /Users/lds/github/elixirstatus-web/rel/elixir_status/releases/0.0.1/elixir_status.sh
Exec: /Users/lds/github/elixirstatus-web/rel/elixir_status/erts-6.2.1/bin/erlexec -boot /Users/lds/github/elixirstatus-web/rel/elixir_status/releases/0.0.1/elixir_status -boot_var ERTS_LIB_DIR /Users/lds/github/elixirstatus-web/rel/elixir_status/erts-6.2.1/../lib -env ERL_LIBS /Users/lds/github/elixirstatus-web/rel/elixir_status/lib -config /Users/lds/github/elixirstatus-web/rel/elixir_status/running-config/sys.config -pa /Users/lds/github/elixirstatus-web/rel/elixir_status/lib/consolidated -args_file /Users/lds/github/elixirstatus-web/rel/elixir_status/running-config/vm.args -user Elixir.IEx.CLI -extra --no-halt +iex -- console
Root: /Users/lds/github/elixirstatus-web/rel/elixir_status
/Users/lds/github/elixirstatus-web/rel/elixir_status
Erlang/OTP 17 [erts-6.2.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

22:53:22.332 [info] Running ElixirStatus.Endpoint with Cowboy on http://sdutlinux.org:4000
Interactive Elixir (1.0.5) - press Ctrl+C to exit (type h() ENTER for help)
iex(elixir_status@127.0.0.1)> 22:53:29.909 [info] GET /
22:53:29.991 [info] Sent 500 in 79ms
22:53:30.023 [error] #PID<0.257.0> running ElixirStatus.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /
** (exit) an exception was raised:
    ** (UndefinedFunctionError) undefined function: Scrivener.paginate/4 (module Scrivener is not available)
        Scrivener.paginate(ElixirStatus.Repo, [page_size: 20], #Ecto.Query<from p in ElixirStatus.Posting, where: p.public == ^true, order_by: [desc: p.published_at], preload: [:user]>, %{"format" => "html"})
        (elixir_status) web/controllers/posting_controller.ex:20: ElixirStatus.PostingController.index/2
        (elixir_status) web/controllers/posting_controller.ex:1: ElixirStatus.PostingController.phoenix_controller_pipeline/2
        (elixir_status) lib/phoenix/router.ex:281: ElixirStatus.Router.dispatch/2
        (elixir_status) web/router.ex:1: ElixirStatus.Router.do_call/2
        (elixir_status) lib/elixir_status/endpoint.ex:1: ElixirStatus.Endpoint.phoenix_endpoint_pipeline/1
        (elixir_status) lib/phoenix/endpoint/render_errors.ex:34: ElixirStatus.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy_handler.ex:80: Phoenix.Endpoint.CowboyHandler.upgrade/4
```

**Comment by feixionglee** [comment]
how you fix that?
